name: main

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - created

env:
  GIT_SHA: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}
  ACTION_TRIGGERED: ${{ github.event_name }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  KUBE_SYSTEM_REPO_URL: git@github.com:szymonrychu/kube-system.git
  BOT_RSA_KEY: ${{ secrets.BOT_RSA_KEY }}

jobs:
  development:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        sudo bash ./get_helm.sh

    - name: Login to dockerhub
      run: |
        echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USERNAME} --password-stdin

    - name: Build docker container
      run: |
        docker build -t ${DOCKERHUB_USERNAME}/vessel_finder_server:${GIT_SHA} .

    - name: Push docker container
      run: |
        docker push ${DOCKERHUB_USERNAME}/vessel_finder_server:${GIT_SHA}
    
    - name: Update helm chart
      run: |
        set -x 
        mkdir -p ~/.ssh/; echo "${BOT_RSA_KEY}" > ~/.ssh/id_rsa; chmod 0600 ~/.ssh/id_rsa
        yq w -i ./chart/vessel-server/Chart.yaml appVersion ${GIT_SHA}



        git clone ${KUBE_SYSTEM_REPO_URL} /tmp/kube-system
        rm -rf /tmp/kube-system/chart/vessel-server
        cp -r ./chart/vessel-server /tmp/kube-system/chart/vessel-server
        cd /tmp/kube-system
        git add -A
        git commit -m "Update vessel-server with version ${GIT_SHA}"
        git push origin master


    

        
